version: '3.9'  # Updated to the latest Compose file version

services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:6.0  # Updated to MongoDB 6.0 (latest stable version)
    ports:
      - "27017:27017"
